# Generated by Django 5.1.7 on 2025-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=255),
            preserve_default=False,
        ),
    ]
