# Generated by Django 5.1.7 on 2025-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=255),
            preserve_default=False,
        ),
    ]
