# Generated by Django 5.1.7 on 2025-07-23 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_userstreak"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
